import React from "react";
import Head from "next/head";

import Menu from "../components/Menu/Menu";
import CodeEditor from "../components/CodeEditor/CodeEditor";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <main className="wrapper">
        <div className="wrapper__container">
          <section className="hero">
            <h1 className="hero__title ">
              Hi, I&apos;m Pablo, Frontend Engineer
            </h1>
            <p className="hero__description">
              Frontend Developer specialized in the development of SPAs using
              React, always following best practices and clean code.
            </p>
            <div className="code-container">
              <CodeEditor />
            </div>
          </section>
        </div>
      </main>
    </>
  );
};

export default Home;
