import React from "react";
import Head from "next/head";

import Menu from "../components/Menu/Menu";
import Layout from "../layout/Layout";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <Layout>
        <div className="hero-wrapper">
          <h1>Hi, I'm Pablo, Frontend Engineer</h1>
        </div>
      </Layout>
    </>
  );
};

export default Home;
